# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ut.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import image

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(474, 398)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(11, 0, 97);\n"
"border-radius: 10px;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 30, 331, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"border: none;\n"
"color: white\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 81, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/utube_logo/ut.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 70, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"border: none;\n"
"color: rgb(199, 34, 12)\n"
"}")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 110, 271, 20))
        self.lineEdit.setTabletTracking(False)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"border: none;\n"
"background-color: rgb(119, 120, 148);\n"
"color: white\n"
"}")
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 150, 271, 20))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"border: none;\n"
"background-color: rgb(119, 120, 148);\n"
"color: white\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 150, 75, 23))
        self.pushButton.setStyleSheet("QPushButton {\n"
"border: none;\n"
"background-color: rgb(52, 66, 255);\n"
"color: white\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(50, 45, 177)\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 110, 75, 23))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"border: none;\n"
"background-color: rgb(52, 66, 255);\n"
"color: white\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(50, 45, 177)\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 51, 21))
        self.label_4.setStyleSheet("QLabel {\n"
"border: none;\n"
"color: white\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 51, 21))
        self.label_5.setStyleSheet("QLabel {\n"
"border: none;\n"
"color: white\n"
"}")
        self.label_5.setObjectName("label_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 340, 75, 23))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"border: none;\n"
"background-color: rgb(52, 66, 255);\n"
"color: white\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(50, 45, 177)\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 250, 261, 20))
        self.label_6.setStyleSheet("QLabel {\n"
"border: none;\n"
"color: white\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(100, 340, 341, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"background-color: rgb(50, 40, 97);\n"
"border-radius: 10px;\n"
"text-align: center;\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid black\n"
"}\n"
"QProgressBar::chunk{\n"
"background-color: rgb(255, 150, 255);\n"
"border-radius: 10px;\n"
"padding: 1px\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(220, 80, 81, 17))
        self.radioButton.setStyleSheet("QRadioButton {\n"
"color: rgb(199, 34, 12)\n"
"}")
        self.radioButton.setObjectName("radioButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 270, 261, 41))
        self.comboBox.setStyleSheet("QComboBox {\n"
"border: none;\n"
"background-color: rgb(119, 120, 148);\n"
"color: white\n"
"}\n"
"QComboBox:hover {\n"
"background-color: rgb(90, 90, 106)\n"
"}")
        self.comboBox.setCurrentText("")
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 320, 431, 20))
        self.label_9.setStyleSheet("QLabel {\n"
"border: none;\n"
"color: white\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 190, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("QTextBrowser {\n"
"border: none;\n"
"color: white;\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(320, 250, 131, 17))
        self.radioButton_2.setStyleSheet("QRadioButton {\n"
"color: white\n"
"}")
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(310, 270, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"border: none;\n"
"color: white\n"
"}")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(420, 270, 41, 16))
        self.label_8.setStyleSheet("QLabel {\n"
"border: none;\n"
"color: white\n"
"}")
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fastest Youtube Video Downloader"))
        self.label.setText(_translate("MainWindow", "Video Downloader"))
        self.label_3.setText(_translate("MainWindow", "- by Salil Agrawal"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "    Enter YouTube URL"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "    Enter Download Path "))
        self.pushButton.setText(_translate("MainWindow", "Browse"))
        self.pushButton_2.setText(_translate("MainWindow", "Submit"))
        self.label_4.setText(_translate("MainWindow", "Video Link"))
        self.label_5.setText(_translate("MainWindow", "Video Path"))
        self.pushButton_3.setText(_translate("MainWindow", "Download"))
        self.label_6.setText(_translate("MainWindow", "Please select the version from the list below"))
        self.radioButton.setText(_translate("MainWindow", "New Window"))
        self.comboBox.setProperty("placeholderText", _translate("MainWindow", " Select a Version to Download"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Video 1080p/mp4"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Video 720p/mp4"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Video 480p/mp4"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Video 360p/mp4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Video 240p/mp4"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Video 144p/mp4"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Audio mp4"))
        self.label_9.setText(_translate("MainWindow", "Downloading Status..."))
        self.radioButton_2.setText(_translate("MainWindow", "Check Internet Speed"))
        self.label_7.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Mbps"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
